# Generated by Django 6.0.5 on 2026-05-13 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructor', '0002_instructor_photo_instructor_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructor',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='instructor',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
